### ISSUE TITLE
Select device type popup not showing correct list

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#27]
The "Select device type" popup at registration shows more device types than what should be returned by matching types. It seems to accumulate a list of device types instead of running the query for the actual device.

**Comment by craigmulligan** [comment]
Relates to https://github.com/Agile-IoT/agile-core/issues/40, I was getting errors on that call which would crash the api, so I instead of doing a query per device and potentially crashing the server, I'd do one query and get all the device types. I can try switch it back if you think it's likely fixed?

**Comment by cskiraly** [comment]
Thanks, I'm looking at it and let you know.

**Comment by cskiraly** [comment]
please try again, and if there are problems, try https://github.com/Agile-IoT/agile-core/blob/ee59c975b3b69d7e17dd8dad4fc156dd7ec244a7/test/http/discovered-devicetypes.sh

**Comment by craigmulligan** [comment]
Okay cool 👍

**Comment by cskiraly** [comment]
please let me know when you have a version I can try.

**Comment by craigmulligan** [comment]
Won't get to it today, likely on be late monday/tuesday.

**Comment by craig-mulligan** [comment]
@cskiraly working for me, is it possible you built it from master and not this branch?
